### ISSUE TITLE
Training in batches

### ISSUE THREAD

**Issue by Labaien96** [xuczhang/tapnet#12]
Hi! Congratulations for this great work. I have a question about how you approach training. I understand that you want to train the model using a single batch, to create the prototypes of the classes considering all the training data, but due to memory issues, I can't load all the dataset in one batch. Does it make sense to take sufficiently large batches and go updating the class prototype in each batch instead of in each epoch?  

Thank you.

**Comment by xuczhang** [comment]
Hi Jokin,

I agree you can update the prototypes for each batch instead of epoch.

Best,
Xuchao

From: Jokin Labaien ***@***.***>
Date: Monday, April 11, 2022 at 6:27 AM
To: xuczhang/tapnet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xuczhang/tapnet] Training in batches (Issue #12)

Hi! Congratulations for this great work. I have a question about how you approach training. I understand that you want to train the model using a single batch, to create the prototypes of the classes considering all the training data, but due to memory issues, I can't load all the dataset in one batch. Does it make sense to take sufficiently large batches and go updating the class prototype in each batch instead of in each epoch?

Thank you.

**Comment by Labaien96** [comment]
Okay, thanks for your quick response! I'm closing this issue
